# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1923c979281f03adbe5917d6b829e84ca7bd78d7e038a5d326d1f86cf519ed15ff79172d5a6d3e789b574df8ee1e0e13e93999ffaa73dd8761032984b22a25f9

test:
  secret_key_base: d086361a0c82abbfdb304d2449ae019c581dfc32c381d73f1c6162c84d8305b0346a1197b4aae94e223dd2cb7a61168d9000569a5afee474e5bda8a6feb0dacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
